/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package community.server;

import configurations.SocketIOConfiguration;
import controllers.*;
import database.DAL;
import io.javalin.Javalin;
import io.javalin.core.JavalinConfig;
import managers.*;
import socketIO.SocketIOServer;

import java.io.FileNotFoundException;

public class App {
    @SuppressWarnings("unused")
    public static void main(String[] args) throws FileNotFoundException {
        var dal = new DAL();
        var socketIOConf = new SocketIOConfiguration().Read();
        var socketIOServer = new SocketIOServer(socketIOConf);

        var usersManager = new UsersManager(dal);
        var categoriesManager = new CategoriesManager(dal);
        var forumsManager = new ForumsManager(dal);
        var topicsManager = new TopicsManager(dal, socketIOServer, usersManager, forumsManager);
        var responsesManager = new ResponseManager(dal, socketIOServer);

        var app = Javalin.create(JavalinConfig::enableCorsForAllOrigins);

        var usersController = new UsersController(app, usersManager);
        var categoriesController = new CategoriesController(app, categoriesManager);
        var forumsController = new ForumsController(app, forumsManager);
        var topicsController = new TopicsController(app, topicsManager);
        var responseController = new ResponsesController(app, responsesManager);

        // SocketIO
        socketIOServer.start();

        // Http server
        app.start(80);
    }
}
