/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package community.server;

import controllers.CategoriesController;
import controllers.UsersController;
import database.DAL;
import io.javalin.Javalin;
import managers.CategoriesManager;
import managers.UsersManager;

public class App {
    @SuppressWarnings("unused")
    public static void main(String[] args) {
        var dal = new DAL();

        var usersManager = new UsersManager(dal);
        var categoriesManager = new CategoriesManager(dal);

        var app = Javalin.create();

        var usersController = new UsersController(app, usersManager);
        var categoriesController = new CategoriesController(app, categoriesManager);

        app.start(80);
    }
}
