/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package community.server;

import controllers.*;
import database.DAL;
import io.javalin.Javalin;
import io.javalin.core.JavalinConfig;
import managers.*;

public class App {
    @SuppressWarnings("unused")
    public static void main(String[] args) {
        var dal = new DAL();

        var usersManager = new UsersManager(dal);
        var categoriesManager = new CategoriesManager(dal);
        var forumsManager = new ForumsManager(dal);
        var topicsManager = new TopicsManager(dal);
        var responsesManager = new ResponseManager(dal);

        var app = Javalin.create(JavalinConfig::enableCorsForAllOrigins);

        var usersController = new UsersController(app, usersManager);
        var categoriesController = new CategoriesController(app, categoriesManager);
        var forumsController = new ForumsController(app, forumsManager);
        var topicsController = new TopicsController(app, topicsManager);
        var responseController = new ResponsesController(app, responsesManager);

        app.start(80);
    }
}
